name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests and code coverage
        run: npm run test

      - name: Upload Playwright Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: packages/*/playwright-report/
          retention-days: 7

      - name: Upload Playwright Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: packages/*/test-results/
          retention-days: 7